language: java
install: /bin/true
sudo: false

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - ./scripts/install_bundle.sh
  - ./scripts/run.sh ./gradlew setupTestableTomcat

script:
  - ./scripts/deploy_modules.sh
  - ./scripts/deploy_temp_libs.sh
  - ../bundles/tomcat-8.0.32/bin/startup.sh
  - tail ../bundles/tomcat-8.0.32/logs/catalina.out
  - travis_wait ./scripts/wait_until_startup.sh
  - tail ../bundles/tomcat-8.0.32/logs/catalina.out
  - ./scripts/run_integration_tests.sh

after_success:
  - ./gradlew coveralls

after_failure:
  - cat ../bundles/tomcat-8.0.32/logs/catalina.out
  - jps